// Microsoft Fluent UI Emoji CDN base URL
export const FLUENT_EMOJI_CDN = 'https://cdn.jsdelivr.net/npm/@fluentui-emoji/flat@latest/assets'

// Quick reactions (first 5)
export const QUICK_REACTIONS = [
  { emoji: '👍', name: 'thumbs_up', label: 'Thumbs Up' },
  { emoji: '😂', name: 'rolling_on_the_floor_laughing', label: 'Laughing' },
  { emoji: '😊', name: 'smiling_face_with_smiling_eyes', label: 'Smiling' },
  { emoji: '😢', name: 'crying_face', label: 'Sad' },
  { emoji: '❤️', name: 'red_heart', label: 'Heart' },
  { emoji: '🔥', name: 'fire', label: 'Fire' },
]

// All available reactions grouped by category
export const ALL_REACTIONS = {
  'Smileys & Emotion': [
    { emoji: '😀', name: 'grinning_face', label: 'Grinning' },
    { emoji: '😃', name: 'grinning_face_with_big_eyes', label: 'Grinning Big Eyes' },
    { emoji: '😄', name: 'grinning_face_with_smiling_eyes', label: 'Grinning Smiling Eyes' },
    { emoji: '😁', name: 'beaming_face_with_smiling_eyes', label: 'Beaming' },
    { emoji: '😆', name: 'grinning_squinting_face', label: 'Grinning Squinting' },
    { emoji: '😅', name: 'grinning_face_with_sweat', label: 'Grinning Sweat' },
    { emoji: '🤣', name: 'rolling_on_the_floor_laughing', label: 'ROFL' },
    { emoji: '😂', name: 'face_with_tears_of_joy', label: 'Tears of Joy' },
    { emoji: '🙂', name: 'slightly_smiling_face', label: 'Slightly Smiling' },
    { emoji: '🙃', name: 'upside_down_face', label: 'Upside Down' },
    { emoji: '😉', name: 'winking_face', label: 'Winking' },
    { emoji: '😊', name: 'smiling_face_with_smiling_eyes', label: 'Smiling Eyes' },
    { emoji: '😇', name: 'smiling_face_with_halo', label: 'Halo' },
    { emoji: '🥰', name: 'smiling_face_with_hearts', label: 'Hearts' },
    { emoji: '😍', name: 'smiling_face_with_heart_eyes', label: 'Heart Eyes' },
    { emoji: '🤩', name: 'star_struck', label: 'Star Struck' },
    { emoji: '😘', name: 'face_blowing_a_kiss', label: 'Blowing Kiss' },
    { emoji: '😗', name: 'kissing_face', label: 'Kissing' },
    { emoji: '😚', name: 'kissing_face_with_closed_eyes', label: 'Kissing Closed Eyes' },
    { emoji: '😙', name: 'kissing_face_with_smiling_eyes', label: 'Kissing Smiling Eyes' },
    { emoji: '🥲', name: 'smiling_face_with_tear', label: 'Smiling Tear' },
    { emoji: '😋', name: 'face_savoring_food', label: 'Savoring Food' },
    { emoji: '😛', name: 'face_with_tongue', label: 'Tongue' },
    { emoji: '😜', name: 'winking_face_with_tongue', label: 'Winking Tongue' },
    { emoji: '🤪', name: 'zany_face', label: 'Zany' },
    { emoji: '😝', name: 'squinting_face_with_tongue', label: 'Squinting Tongue' },
    { emoji: '🤑', name: 'money_mouth_face', label: 'Money Mouth' },
    { emoji: '🤗', name: 'hugging_face', label: 'Hugging' },
    { emoji: '🤭', name: 'face_with_hand_over_mouth', label: 'Hand Over Mouth' },
    { emoji: '🤫', name: 'shushing_face', label: 'Shushing' },
    { emoji: '🤔', name: 'thinking_face', label: 'Thinking' },
    { emoji: '🤐', name: 'zipper_mouth_face', label: 'Zipper Mouth' },
    { emoji: '🤨', name: 'face_with_raised_eyebrow', label: 'Raised Eyebrow' },
    { emoji: '😐', name: 'neutral_face', label: 'Neutral' },
    { emoji: '😑', name: 'expressionless_face', label: 'Expressionless' },
    { emoji: '😶', name: 'face_without_mouth', label: 'No Mouth' },
    { emoji: '😶‍🌫️', name: 'face_in_clouds', label: 'Face in Clouds' },
    { emoji: '😏', name: 'smirking_face', label: 'Smirking' },
    { emoji: '😒', name: 'unamused_face', label: 'Unamused' },
    { emoji: '🙄', name: 'face_with_rolling_eyes', label: 'Rolling Eyes' },
    { emoji: '😬', name: 'grimacing_face', label: 'Grimacing' },
    { emoji: '😮‍💨', name: 'face_exhaling', label: 'Exhaling' },
    { emoji: '🤥', name: 'lying_face', label: 'Lying' },
    { emoji: '😌', name: 'relieved_face', label: 'Relieved' },
    { emoji: '😔', name: 'pensive_face', label: 'Pensive' },
    { emoji: '😪', name: 'sleepy_face', label: 'Sleepy' },
    { emoji: '🤤', name: 'drooling_face', label: 'Drooling' },
    { emoji: '😴', name: 'sleeping_face', label: 'Sleeping' },
    { emoji: '😷', name: 'face_with_medical_mask', label: 'Medical Mask' },
    { emoji: '🤒', name: 'face_with_thermometer', label: 'Thermometer' },
    { emoji: '🤕', name: 'face_with_head_bandage', label: 'Head Bandage' },
    { emoji: '🤢', name: 'nauseated_face', label: 'Nauseated' },
    { emoji: '🤮', name: 'face_vomiting', label: 'Vomiting' },
    { emoji: '🤧', name: 'sneezing_face', label: 'Sneezing' },
    { emoji: '🥵', name: 'hot_face', label: 'Hot' },
    { emoji: '🥶', name: 'cold_face', label: 'Cold' },
    { emoji: '🥴', name: 'woozy_face', label: 'Woozy' },
    { emoji: '😵', name: 'dizzy_face', label: 'Dizzy' },
    { emoji: '😵‍💫', name: 'face_with_spiral_eyes', label: 'Spiral Eyes' },
    { emoji: '🤯', name: 'exploding_head', label: 'Exploding Head' },
    { emoji: '🤠', name: 'cowboy_hat_face', label: 'Cowboy' },
    { emoji: '🥳', name: 'partying_face', label: 'Partying' },
    { emoji: '🥸', name: 'disguised_face', label: 'Disguised' },
    { emoji: '😎', name: 'smiling_face_with_sunglasses', label: 'Sunglasses' },
    { emoji: '🤓', name: 'nerd_face', label: 'Nerd' },
    { emoji: '🧐', name: 'face_with_monocle', label: 'Monocle' },
    { emoji: '😕', name: 'confused_face', label: 'Confused' },
    { emoji: '😟', name: 'worried_face', label: 'Worried' },
    { emoji: '🙁', name: 'slightly_frowning_face', label: 'Slightly Frowning' },
    { emoji: '☹️', name: 'frowning_face', label: 'Frowning' },
    { emoji: '😮', name: 'face_with_open_mouth', label: 'Open Mouth' },
    { emoji: '😯', name: 'hushed_face', label: 'Hushed' },
    { emoji: '😲', name: 'astonished_face', label: 'Astonished' },
    { emoji: '😳', name: 'flushed_face', label: 'Flushed' },
    { emoji: '🥺', name: 'pleading_face', label: 'Pleading' },
    { emoji: '😦', name: 'frowning_face_with_open_mouth', label: 'Frowning Open Mouth' },
    { emoji: '😧', name: 'anguished_face', label: 'Anguished' },
    { emoji: '😨', name: 'fearful_face', label: 'Fearful' },
    { emoji: '😰', name: 'anxious_face_with_sweat', label: 'Anxious Sweat' },
    { emoji: '😥', name: 'sad_but_relieved_face', label: 'Sad Relieved' },
    { emoji: '😢', name: 'crying_face', label: 'Crying' },
    { emoji: '😭', name: 'loudly_crying_face', label: 'Loudly Crying' },
    { emoji: '😱', name: 'face_screaming_in_fear', label: 'Screaming' },
    { emoji: '😖', name: 'confounded_face', label: 'Confounded' },
    { emoji: '😣', name: 'persevering_face', label: 'Persevering' },
    { emoji: '😞', name: 'disappointed_face', label: 'Disappointed' },
    { emoji: '😓', name: 'downcast_face_with_sweat', label: 'Downcast Sweat' },
    { emoji: '😩', name: 'weary_face', label: 'Weary' },
    { emoji: '😫', name: 'tired_face', label: 'Tired' },
    { emoji: '🥱', name: 'yawning_face', label: 'Yawning' },
    { emoji: '😤', name: 'face_with_steam_from_nose', label: 'Steam From Nose' },
    { emoji: '😡', name: 'pouting_face', label: 'Pouting' },
    { emoji: '😠', name: 'angry_face', label: 'Angry' },
    { emoji: '🤬', name: 'face_with_symbols_on_mouth', label: 'Symbols On Mouth' },
    { emoji: '😈', name: 'smiling_face_with_horns', label: 'Devil Smiling' },
    { emoji: '👿', name: 'angry_face_with_horns', label: 'Devil Angry' },
    { emoji: '💀', name: 'skull', label: 'Skull' },
    { emoji: '☠️', name: 'skull_and_crossbones', label: 'Skull Crossbones' },
    { emoji: '💩', name: 'pile_of_poo', label: 'Poop' },
    { emoji: '🤡', name: 'clown_face', label: 'Clown' },
    { emoji: '👹', name: 'ogre', label: 'Ogre' },
    { emoji: '👺', name: 'goblin', label: 'Goblin' },
    { emoji: '👻', name: 'ghost', label: 'Ghost' },
    { emoji: '👽', name: 'alien', label: 'Alien' },
    { emoji: '👾', name: 'alien_monster', label: 'Space Invader' },
    { emoji: '🤖', name: 'robot', label: 'Robot' },
    { emoji: '😺', name: 'grinning_cat', label: 'Grinning Cat' },
    { emoji: '😸', name: 'grinning_cat_with_smiling_eyes', label: 'Smiling Cat' },
    { emoji: '😹', name: 'cat_with_tears_of_joy', label: 'Laughing Cat' },
    { emoji: '😻', name: 'smiling_cat_with_heart_eyes', label: 'Heart Eyes Cat' },
    { emoji: '😼', name: 'cat_with_wry_smile', label: 'Smirking Cat' },
    { emoji: '😽', name: 'kissing_cat', label: 'Kissing Cat' },
    { emoji: '🙀', name: 'weary_cat', label: 'Weary Cat' },
    { emoji: '😿', name: 'crying_cat', label: 'Crying Cat' },
    { emoji: '😾', name: 'pouting_cat', label: 'Pouting Cat' },
  ],
  'Gestures & Body': [
    { emoji: '🤚', name: 'raised_back_of_hand', label: 'Raised Back' },
    { emoji: '🖐️', name: 'hand_with_fingers_splayed', label: 'Splayed Hand' },
    { emoji: '✋', name: 'raised_hand', label: 'Raised Hand' },
    { emoji: '🖖', name: 'vulcan_salute', label: 'Vulcan Salute' },
    { emoji: '👌', name: 'ok_hand', label: 'OK' },
    { emoji: '🤌', name: 'pinched_fingers', label: 'Pinched Fingers' },
    { emoji: '🤏', name: 'pinching_hand', label: 'Pinching' },
    { emoji: '✌️', name: 'victory_hand', label: 'Victory' },
    { emoji: '🤞', name: 'crossed_fingers', label: 'Crossed Fingers' },
    { emoji: '🤟', name: 'love_you_gesture', label: 'Love You' },
    { emoji: '🤘', name: 'sign_of_the_horns', label: 'Rock On' },
    { emoji: '🤙', name: 'call_me_hand', label: 'Call Me' },
    { emoji: '👈', name: 'backhand_index_pointing_left', label: 'Point Left' },
    { emoji: '👉', name: 'backhand_index_pointing_right', label: 'Point Right' },
    { emoji: '👆', name: 'backhand_index_pointing_up', label: 'Point Up' },
    { emoji: '🖕', name: 'middle_finger', label: 'Middle Finger' },
    { emoji: '👇', name: 'backhand_index_pointing_down', label: 'Point Down' },
    { emoji: '☝️', name: 'index_pointing_up', label: 'Index Up' },
    { emoji: '👍', name: 'thumbs_up', label: 'Thumbs Up' },
    { emoji: '👎', name: 'thumbs_down', label: 'Thumbs Down' },
    { emoji: '✊', name: 'raised_fist', label: 'Raised Fist' },
    { emoji: '👊', name: 'oncoming_fist', label: 'Fist Bump' },
    { emoji: '🤛', name: 'left_facing_fist', label: 'Left Fist' },
    { emoji: '🤜', name: 'right_facing_fist', label: 'Right Fist' },
    { emoji: '👏', name: 'clapping_hands', label: 'Clapping' },
    { emoji: '🙌', name: 'raising_hands', label: 'Raising Hands' },
    { emoji: '👐', name: 'open_hands', label: 'Open Hands' },
    { emoji: '🤲', name: 'palms_up_together', label: 'Palms Up' },
    { emoji: '🤝', name: 'handshake', label: 'Handshake' },
    { emoji: '🙏', name: 'folded_hands', label: 'Folded Hands' },
    { emoji: '✍️', name: 'writing_hand', label: 'Writing' },
    { emoji: '💅', name: 'nail_polish', label: 'Nail Polish' },
    { emoji: '🤳', name: 'selfie', label: 'Selfie' },
    { emoji: '💪', name: 'flexed_biceps', label: 'Muscle' },
    { emoji: '🦾', name: 'mechanical_arm', label: 'Mechanical Arm' },
    { emoji: '🦿', name: 'mechanical_leg', label: 'Mechanical Leg' },
    { emoji: '🦵', name: 'leg', label: 'Leg' },
    { emoji: '🦶', name: 'foot', label: 'Foot' },
    { emoji: '👂', name: 'ear', label: 'Ear' },
    { emoji: '🦻', name: 'ear_with_hearing_aid', label: 'Hearing Aid' },
    { emoji: '👃', name: 'nose', label: 'Nose' },
    { emoji: '🧠', name: 'brain', label: 'Brain' },
    { emoji: '🫀', name: 'anatomical_heart', label: 'Heart' },
    { emoji: '🫁', name: 'lungs', label: 'Lungs' },
    { emoji: '🦷', name: 'tooth', label: 'Tooth' },
    { emoji: '🦴', name: 'bone', label: 'Bone' },
    { emoji: '👀', name: 'eyes', label: 'Eyes' },
    { emoji: '👁️', name: 'eye', label: 'Eye' },
    { emoji: '👅', name: 'tongue', label: 'Tongue' },
    { emoji: '👄', name: 'mouth', label: 'Mouth' },
  ],
  'Hearts & Love': [
    { emoji: '❤️', name: 'red_heart', label: 'Red Heart' },
    { emoji: '🧡', name: 'orange_heart', label: 'Orange Heart' },
    { emoji: '💛', name: 'yellow_heart', label: 'Yellow Heart' },
    { emoji: '💚', name: 'green_heart', label: 'Green Heart' },
    { emoji: '💙', name: 'blue_heart', label: 'Blue Heart' },
    { emoji: '💜', name: 'purple_heart', label: 'Purple Heart' },
    { emoji: '🖤', name: 'black_heart', label: 'Black Heart' },
    { emoji: '🤍', name: 'white_heart', label: 'White Heart' },
    { emoji: '🤎', name: 'brown_heart', label: 'Brown Heart' },
    { emoji: '💔', name: 'broken_heart', label: 'Broken Heart' },
    { emoji: '❣️', name: 'heart_exclamation', label: 'Heart Exclamation' },
    { emoji: '💕', name: 'two_hearts', label: 'Two Hearts' },
    { emoji: '💞', name: 'revolving_hearts', label: 'Revolving Hearts' },
    { emoji: '💓', name: 'beating_heart', label: 'Beating Heart' },
    { emoji: '💗', name: 'growing_heart', label: 'Growing Heart' },
    { emoji: '💖', name: 'sparkling_heart', label: 'Sparkling Heart' },
    { emoji: '💘', name: 'heart_with_arrow', label: 'Heart With Arrow' },
    { emoji: '💝', name: 'heart_with_ribbon', label: 'Heart With Ribbon' },
  ],
  'Objects & Symbols': [
    { emoji: '🔥', name: 'fire', label: 'Fire' },
    { emoji: '⭐', name: 'star', label: 'Star' },
    { emoji: '✨', name: 'sparkles', label: 'Sparkles' },
    { emoji: '💯', name: 'hundred_points', label: '100' },
    { emoji: '💢', name: 'anger_symbol', label: 'Anger' },
    { emoji: '💥', name: 'collision', label: 'Collision' },
    { emoji: '💫', name: 'dizzy', label: 'Dizzy' },
    { emoji: '💦', name: 'sweat_droplets', label: 'Sweat' },
    { emoji: '💨', name: 'dashing_away', label: 'Dashing' },
    { emoji: '🎉', name: 'party_popper', label: 'Party' },
    { emoji: '🎊', name: 'confetti_ball', label: 'Confetti' },
    { emoji: '🎈', name: 'balloon', label: 'Balloon' },
    { emoji: '🎁', name: 'wrapped_gift', label: 'Gift' },
    { emoji: '🏆', name: 'trophy', label: 'Trophy' },
    { emoji: '🥇', name: 'first_place_medal', label: '1st Place' },
    { emoji: '🥈', name: 'second_place_medal', label: '2nd Place' },
    { emoji: '🥉', name: 'third_place_medal', label: '3rd Place' },
    { emoji: '⚽', name: 'soccer_ball', label: 'Soccer' },
    { emoji: '⚾', name: 'baseball', label: 'Baseball' },
    { emoji: '🥎', name: 'softball', label: 'Softball' },
    { emoji: '🏀', name: 'basketball', label: 'Basketball' },
    { emoji: '🏐', name: 'volleyball', label: 'Volleyball' },
    { emoji: '🏈', name: 'american_football', label: 'Football' },
    { emoji: '🏉', name: 'rugby_football', label: 'Rugby' },
    { emoji: '🎾', name: 'tennis', label: 'Tennis' },
    { emoji: '🥏', name: 'flying_disc', label: 'Frisbee' },
    { emoji: '🎳', name: 'bowling', label: 'Bowling' },
    { emoji: '🏏', name: 'cricket_game', label: 'Cricket' },
    { emoji: '🏑', name: 'field_hockey', label: 'Hockey' },
    { emoji: '🏒', name: 'ice_hockey', label: 'Ice Hockey' },
    { emoji: '🥍', name: 'lacrosse', label: 'Lacrosse' },
    { emoji: '🏓', name: 'ping_pong', label: 'Ping Pong' },
    { emoji: '🏸', name: 'badminton', label: 'Badminton' },
    { emoji: '🥊', name: 'boxing_glove', label: 'Boxing' },
    { emoji: '🥋', name: 'martial_arts_uniform', label: 'Martial Arts' },
    { emoji: '🥅', name: 'goal_net', label: 'Goal' },
    { emoji: '⛳', name: 'flag_in_hole', label: 'Golf' },
    { emoji: '⛸️', name: 'ice_skate', label: 'Ice Skate' },
    { emoji: '🎣', name: 'fishing_pole', label: 'Fishing' },
    { emoji: '🤿', name: 'diving_mask', label: 'Diving' },
    { emoji: '🎽', name: 'running_shirt', label: 'Running' },
    { emoji: '🎿', name: 'skis', label: 'Skiing' },
    { emoji: '🛷', name: 'sled', label: 'Sledding' },
    { emoji: '🥌', name: 'curling_stone', label: 'Curling' },
    { emoji: '🎯', name: 'direct_hit', label: 'Bullseye' },
    { emoji: '🪀', name: 'yo_yo', label: 'Yo-Yo' },
    { emoji: '🪁', name: 'kite', label: 'Kite' },
    { emoji: '🎱', name: 'pool_8_ball', label: '8 Ball' },
    { emoji: '🔮', name: 'crystal_ball', label: 'Crystal Ball' },
    { emoji: '🪄', name: 'magic_wand', label: 'Magic Wand' },
    { emoji: '🧿', name: 'nazar_amulet', label: 'Evil Eye' },
    { emoji: '🎮', name: 'video_game', label: 'Gaming' },
    { emoji: '🕹️', name: 'joystick', label: 'Joystick' },
    { emoji: '🎰', name: 'slot_machine', label: 'Slot Machine' },
    { emoji: '🎲', name: 'game_die', label: 'Dice' },
    { emoji: '🧩', name: 'puzzle_piece', label: 'Puzzle' },
    { emoji: '🧸', name: 'teddy_bear', label: 'Teddy Bear' },
    { emoji: '🪅', name: 'pinata', label: 'Pinata' },
    { emoji: '🪆', name: 'nesting_dolls', label: 'Nesting Dolls' },
    { emoji: '♠️', name: 'spade_suit', label: 'Spades' },
    { emoji: '♥️', name: 'heart_suit', label: 'Hearts' },
    { emoji: '♦️', name: 'diamond_suit', label: 'Diamonds' },
    { emoji: '♣️', name: 'club_suit', label: 'Clubs' },
    { emoji: '♟️', name: 'chess_pawn', label: 'Chess' },
    { emoji: '🃏', name: 'joker', label: 'Joker' },
    { emoji: '🀄', name: 'mahjong_red_dragon', label: 'Mahjong' },
    { emoji: '🎴', name: 'flower_playing_cards', label: 'Cards' },
  ],
  'Animals & Nature': [
    { emoji: '🐶', name: 'dog_face', label: 'Dog' },
    { emoji: '🐱', name: 'cat_face', label: 'Cat' },
    { emoji: '🐭', name: 'mouse_face', label: 'Mouse' },
    { emoji: '🐹', name: 'hamster', label: 'Hamster' },
    { emoji: '🐰', name: 'rabbit_face', label: 'Rabbit' },
    { emoji: '🦊', name: 'fox', label: 'Fox' },
    { emoji: '🐻', name: 'bear', label: 'Bear' },
    { emoji: '🐼', name: 'panda', label: 'Panda' },
    { emoji: '🐻‍❄️', name: 'polar_bear', label: 'Polar Bear' },
    { emoji: '🐨', name: 'koala', label: 'Koala' },
    { emoji: '🐯', name: 'tiger_face', label: 'Tiger' },
    { emoji: '🦁', name: 'lion', label: 'Lion' },
    { emoji: '🐮', name: 'cow_face', label: 'Cow' },
    { emoji: '🐷', name: 'pig_face', label: 'Pig' },
    { emoji: '🐽', name: 'pig_nose', label: 'Pig Nose' },
    { emoji: '🐸', name: 'frog', label: 'Frog' },
    { emoji: '🐵', name: 'monkey_face', label: 'Monkey' },
    { emoji: '🙈', name: 'see_no_evil_monkey', label: 'See No Evil' },
    { emoji: '🙉', name: 'hear_no_evil_monkey', label: 'Hear No Evil' },
    { emoji: '🙊', name: 'speak_no_evil_monkey', label: 'Speak No Evil' },
    { emoji: '🐒', name: 'monkey', label: 'Monkey Full' },
    { emoji: '🦍', name: 'gorilla', label: 'Gorilla' },
    { emoji: '🦧', name: 'orangutan', label: 'Orangutan' },
    { emoji: '🐔', name: 'chicken', label: 'Chicken' },
    { emoji: '🐧', name: 'penguin', label: 'Penguin' },
    { emoji: '🐦', name: 'bird', label: 'Bird' },
    { emoji: '🐤', name: 'baby_chick', label: 'Baby Chick' },
    { emoji: '🐣', name: 'hatching_chick', label: 'Hatching Chick' },
    { emoji: '🐥', name: 'front_facing_baby_chick', label: 'Front Chick' },
    { emoji: '🦆', name: 'duck', label: 'Duck' },
    { emoji: '🦅', name: 'eagle', label: 'Eagle' },
    { emoji: '🦉', name: 'owl', label: 'Owl' },
    { emoji: '🦇', name: 'bat', label: 'Bat' },
    { emoji: '🐺', name: 'wolf', label: 'Wolf' },
    { emoji: '🐗', name: 'boar', label: 'Boar' },
    { emoji: '🐴', name: 'horse_face', label: 'Horse' },
    { emoji: '🦄', name: 'unicorn', label: 'Unicorn' },
    { emoji: '🐝', name: 'honeybee', label: 'Bee' },
    { emoji: '🪱', name: 'worm', label: 'Worm' },
    { emoji: '🐛', name: 'bug', label: 'Bug' },
    { emoji: '🦋', name: 'butterfly', label: 'Butterfly' },
    { emoji: '🐌', name: 'snail', label: 'Snail' },
    { emoji: '🐞', name: 'lady_beetle', label: 'Ladybug' },
    { emoji: '🐜', name: 'ant', label: 'Ant' },
    { emoji: '🪰', name: 'fly', label: 'Fly' },
    { emoji: '🪲', name: 'beetle', label: 'Beetle' },
    { emoji: '🪳', name: 'cockroach', label: 'Cockroach' },
    { emoji: '🦟', name: 'mosquito', label: 'Mosquito' },
    { emoji: '🦗', name: 'cricket', label: 'Cricket' },
    { emoji: '🕷️', name: 'spider', label: 'Spider' },
    { emoji: '🕸️', name: 'spider_web', label: 'Spider Web' },
    { emoji: '🦂', name: 'scorpion', label: 'Scorpion' },
    { emoji: '🐢', name: 'turtle', label: 'Turtle' },
    { emoji: '🐍', name: 'snake', label: 'Snake' },
    { emoji: '🦎', name: 'lizard', label: 'Lizard' },
    { emoji: '🦖', name: 't_rex', label: 'T-Rex' },
    { emoji: '🦕', name: 'sauropod', label: 'Dinosaur' },
    { emoji: '🐙', name: 'octopus', label: 'Octopus' },
    { emoji: '🦑', name: 'squid', label: 'Squid' },
    { emoji: '🦐', name: 'shrimp', label: 'Shrimp' },
    { emoji: '🦞', name: 'lobster', label: 'Lobster' },
    { emoji: '🦀', name: 'crab', label: 'Crab' },
    { emoji: '🐡', name: 'blowfish', label: 'Blowfish' },
    { emoji: '🐠', name: 'tropical_fish', label: 'Tropical Fish' },
    { emoji: '🐟', name: 'fish', label: 'Fish' },
    { emoji: '🐬', name: 'dolphin', label: 'Dolphin' },
    { emoji: '🐳', name: 'spouting_whale', label: 'Whale' },
    { emoji: '🐋', name: 'whale', label: 'Whale Full' },
    { emoji: '🦈', name: 'shark', label: 'Shark' },
    { emoji: '🐊', name: 'crocodile', label: 'Crocodile' },
    { emoji: '🐅', name: 'tiger', label: 'Tiger Full' },
    { emoji: '🐆', name: 'leopard', label: 'Leopard' },
    { emoji: '🦓', name: 'zebra', label: 'Zebra' },
    { emoji: '🦍', name: 'gorilla', label: 'Gorilla' },
    { emoji: '🦘', name: 'kangaroo', label: 'Kangaroo' },
    { emoji: '🦬', name: 'bison', label: 'Bison' },
    { emoji: '🐃', name: 'water_buffalo', label: 'Buffalo' },
    { emoji: '🐂', name: 'ox', label: 'Ox' },
    { emoji: '🐄', name: 'cow', label: 'Cow Full' },
    { emoji: '🐎', name: 'horse', label: 'Horse Full' },
    { emoji: '🐖', name: 'pig', label: 'Pig Full' },
    { emoji: '🐏', name: 'ram', label: 'Ram' },
    { emoji: '🐑', name: 'ewe', label: 'Sheep' },
    { emoji: '🦙', name: 'llama', label: 'Llama' },
    { emoji: '🐐', name: 'goat', label: 'Goat' },
    { emoji: '🦌', name: 'deer', label: 'Deer' },
    { emoji: '🐕', name: 'dog', label: 'Dog Full' },
    { emoji: '🐩', name: 'poodle', label: 'Poodle' },
    { emoji: '🦮', name: 'guide_dog', label: 'Guide Dog' },
    { emoji: '🐕‍🦺', name: 'service_dog', label: 'Service Dog' },
    { emoji: '🐈', name: 'cat', label: 'Cat Full' },
    { emoji: '🐈‍⬛', name: 'black_cat', label: 'Black Cat' },
    { emoji: '🪶', name: 'feather', label: 'Feather' },
    { emoji: '🐓', name: 'rooster', label: 'Rooster' },
    { emoji: '🦃', name: 'turkey', label: 'Turkey' },
    { emoji: '🦤', name: 'dodo', label: 'Dodo' },
    { emoji: '🦚', name: 'peacock', label: 'Peacock' },
    { emoji: '🦜', name: 'parrot', label: 'Parrot' },
    { emoji: '🦢', name: 'swan', label: 'Swan' },
    { emoji: '🦩', name: 'flamingo', label: 'Flamingo' },
    { emoji: '🕊️', name: 'dove', label: 'Dove' },
    { emoji: '🐇', name: 'rabbit', label: 'Rabbit Full' },
    { emoji: '🦝', name: 'raccoon', label: 'Raccoon' },
    { emoji: '🦨', name: 'skunk', label: 'Skunk' },
    { emoji: '🦡', name: 'badger', label: 'Badger' },
    { emoji: '🦫', name: 'beaver', label: 'Beaver' },
    { emoji: '🦦', name: 'otter', label: 'Otter' },
    { emoji: '🦥', name: 'sloth', label: 'Sloth' },
    { emoji: '🐁', name: 'mouse', label: 'Mouse Full' },
    { emoji: '🐀', name: 'rat', label: 'Rat' },
    { emoji: '🐿️', name: 'chipmunk', label: 'Chipmunk' },
    { emoji: '🦔', name: 'hedgehog', label: 'Hedgehog' },
    { emoji: '🐾', name: 'paw_prints', label: 'Paw Prints' },
    { emoji: '🐉', name: 'dragon', label: 'Dragon' },
    { emoji: '🐲', name: 'dragon_face', label: 'Dragon Face' },
    { emoji: '🌵', name: 'cactus', label: 'Cactus' },
    { emoji: '🎄', name: 'christmas_tree', label: 'Christmas Tree' },
    { emoji: '🌲', name: 'evergreen_tree', label: 'Evergreen' },
    { emoji: '🌳', name: 'deciduous_tree', label: 'Tree' },
    { emoji: '🌴', name: 'palm_tree', label: 'Palm Tree' },
    { emoji: '🪵', name: 'wood', label: 'Wood' },
    { emoji: '🌱', name: 'seedling', label: 'Seedling' },
    { emoji: '🌿', name: 'herb', label: 'Herb' },
    { emoji: '☘️', name: 'shamrock', label: 'Shamrock' },
    { emoji: '🍀', name: 'four_leaf_clover', label: 'Four Leaf Clover' },
    { emoji: '🎍', name: 'pine_decoration', label: 'Pine Decoration' },
    { emoji: '🪴', name: 'potted_plant', label: 'Potted Plant' },
    { emoji: '🎋', name: 'tanabata_tree', label: 'Tanabata Tree' },
    { emoji: '🍃', name: 'leaf_fluttering_in_wind', label: 'Leaves' },
    { emoji: '🍂', name: 'fallen_leaf', label: 'Fallen Leaf' },
    { emoji: '🍁', name: 'maple_leaf', label: 'Maple Leaf' },
    { emoji: '🪺', name: 'nest_with_eggs', label: 'Nest' },
    { emoji: '🪹', name: 'empty_nest', label: 'Empty Nest' },
  ],
  'Food & Drink': [
    { emoji: '🍇', name: 'grapes', label: 'Grapes' },
    { emoji: '🍈', name: 'melon', label: 'Melon' },
    { emoji: '🍉', name: 'watermelon', label: 'Watermelon' },
    { emoji: '🍊', name: 'tangerine', label: 'Tangerine' },
    { emoji: '🍋', name: 'lemon', label: 'Lemon' },
    { emoji: '🍌', name: 'banana', label: 'Banana' },
    { emoji: '🍍', name: 'pineapple', label: 'Pineapple' },
    { emoji: '🥭', name: 'mango', label: 'Mango' },
    { emoji: '🍎', name: 'red_apple', label: 'Red Apple' },
    { emoji: '🍏', name: 'green_apple', label: 'Green Apple' },
    { emoji: '🍐', name: 'pear', label: 'Pear' },
    { emoji: '🍑', name: 'peach', label: 'Peach' },
    { emoji: '🍒', name: 'cherries', label: 'Cherries' },
    { emoji: '🍓', name: 'strawberry', label: 'Strawberry' },
    { emoji: '🫐', name: 'blueberries', label: 'Blueberries' },
    { emoji: '🥝', name: 'kiwi_fruit', label: 'Kiwi' },
    { emoji: '🍅', name: 'tomato', label: 'Tomato' },
    { emoji: '🫒', name: 'olive', label: 'Olive' },
    { emoji: '🥥', name: 'coconut', label: 'Coconut' },
    { emoji: '🥑', name: 'avocado', label: 'Avocado' },
    { emoji: '🍆', name: 'eggplant', label: 'Eggplant' },
    { emoji: '🥔', name: 'potato', label: 'Potato' },
    { emoji: '🥕', name: 'carrot', label: 'Carrot' },
    { emoji: '🌽', name: 'ear_of_corn', label: 'Corn' },
    { emoji: '🌶️', name: 'hot_pepper', label: 'Hot Pepper' },
    { emoji: '🫑', name: 'bell_pepper', label: 'Bell Pepper' },
    { emoji: '🥒', name: 'cucumber', label: 'Cucumber' },
    { emoji: '🥬', name: 'leafy_green', label: 'Leafy Green' },
    { emoji: '🥦', name: 'broccoli', label: 'Broccoli' },
    { emoji: '🧄', name: 'garlic', label: 'Garlic' },
    { emoji: '🧅', name: 'onion', label: 'Onion' },
    { emoji: '🍄', name: 'mushroom', label: 'Mushroom' },
    { emoji: '🥜', name: 'peanuts', label: 'Peanuts' },
    { emoji: '🫘', name: 'beans', label: 'Beans' },
    { emoji: '🌰', name: 'chestnut', label: 'Chestnut' },
    { emoji: '🍞', name: 'bread', label: 'Bread' },
    { emoji: '🥐', name: 'croissant', label: 'Croissant' },
    { emoji: '🥖', name: 'baguette_bread', label: 'Baguette' },
    { emoji: '🫓', name: 'flatbread', label: 'Flatbread' },
    { emoji: '🥨', name: 'pretzel', label: 'Pretzel' },
    { emoji: '🥯', name: 'bagel', label: 'Bagel' },
    { emoji: '🥞', name: 'pancakes', label: 'Pancakes' },
    { emoji: '🧇', name: 'waffle', label: 'Waffle' },
    { emoji: '🧀', name: 'cheese_wedge', label: 'Cheese' },
    { emoji: '🍖', name: 'meat_on_bone', label: 'Meat on Bone' },
    { emoji: '🍗', name: 'poultry_leg', label: 'Poultry' },
    { emoji: '🥩', name: 'cut_of_meat', label: 'Steak' },
    { emoji: '🥓', name: 'bacon', label: 'Bacon' },
    { emoji: '🍔', name: 'hamburger', label: 'Hamburger' },
    { emoji: '🍟', name: 'french_fries', label: 'Fries' },
    { emoji: '🍕', name: 'pizza', label: 'Pizza' },
    { emoji: '🌭', name: 'hot_dog', label: 'Hot Dog' },
    { emoji: '🥪', name: 'sandwich', label: 'Sandwich' },
    { emoji: '🌮', name: 'taco', label: 'Taco' },
    { emoji: '🌯', name: 'burrito', label: 'Burrito' },
    { emoji: '🫔', name: 'tamale', label: 'Tamale' },
    { emoji: '🥙', name: 'stuffed_flatbread', label: 'Stuffed Flatbread' },
    { emoji: '🧆', name: 'falafel', label: 'Falafel' },
    { emoji: '🥚', name: 'egg', label: 'Egg' },
    { emoji: '🍳', name: 'cooking', label: 'Cooking' },
    { emoji: '🥘', name: 'shallow_pan_of_food', label: 'Pan of Food' },
    { emoji: '🍲', name: 'pot_of_food', label: 'Pot of Food' },
    { emoji: '🫕', name: 'fondue', label: 'Fondue' },
    { emoji: '🥣', name: 'bowl_with_spoon', label: 'Bowl with Spoon' },
    { emoji: '🥗', name: 'green_salad', label: 'Salad' },
    { emoji: '🍿', name: 'popcorn', label: 'Popcorn' },
    { emoji: '🧈', name: 'butter', label: 'Butter' },
    { emoji: '🧂', name: 'salt', label: 'Salt' },
    { emoji: '🥫', name: 'canned_food', label: 'Canned Food' },
    { emoji: '🍱', name: 'bento_box', label: 'Bento Box' },
    { emoji: '🍘', name: 'rice_cracker', label: 'Rice Cracker' },
    { emoji: '🍙', name: 'rice_ball', label: 'Rice Ball' },
    { emoji: '🍚', name: 'cooked_rice', label: 'Rice' },
    { emoji: '🍛', name: 'curry_rice', label: 'Curry' },
    { emoji: '🍜', name: 'steaming_bowl', label: 'Ramen' },
    { emoji: '🍝', name: 'spaghetti', label: 'Spaghetti' },
    { emoji: '🍠', name: 'roasted_sweet_potato', label: 'Sweet Potato' },
    { emoji: '🍢', name: 'oden', label: 'Oden' },
    { emoji: '🍣', name: 'sushi', label: 'Sushi' },
    { emoji: '🍤', name: 'fried_shrimp', label: 'Fried Shrimp' },
    { emoji: '🍥', name: 'fish_cake_with_swirl', label: 'Fish Cake' },
    { emoji: '🥮', name: 'moon_cake', label: 'Moon Cake' },
    { emoji: '🍡', name: 'dango', label: 'Dango' },
    { emoji: '🥟', name: 'dumpling', label: 'Dumpling' },
    { emoji: '🥠', name: 'fortune_cookie', label: 'Fortune Cookie' },
    { emoji: '🥡', name: 'takeout_box', label: 'Takeout Box' },
    { emoji: '🦀', name: 'crab', label: 'Crab' },
    { emoji: '🦞', name: 'lobster', label: 'Lobster' },
    { emoji: '🦐', name: 'shrimp', label: 'Shrimp' },
    { emoji: '🦑', name: 'squid', label: 'Squid' },
    { emoji: '🦪', name: 'oyster', label: 'Oyster' },
    { emoji: '🍦', name: 'soft_ice_cream', label: 'Ice Cream' },
    { emoji: '🍧', name: 'shaved_ice', label: 'Shaved Ice' },
    { emoji: '🍨', name: 'ice_cream', label: 'Ice Cream Bowl' },
    { emoji: '🍩', name: 'doughnut', label: 'Doughnut' },
    { emoji: '🍪', name: 'cookie', label: 'Cookie' },
    { emoji: '🎂', name: 'birthday_cake', label: 'Birthday Cake' },
    { emoji: '🍰', name: 'shortcake', label: 'Cake' },
    { emoji: '🧁', name: 'cupcake', label: 'Cupcake' },
    { emoji: '🥧', name: 'pie', label: 'Pie' },
    { emoji: '🍫', name: 'chocolate_bar', label: 'Chocolate' },
    { emoji: '🍬', name: 'candy', label: 'Candy' },
    { emoji: '🍭', name: 'lollipop', label: 'Lollipop' },
    { emoji: '🍮', name: 'custard', label: 'Custard' },
    { emoji: '🍯', name: 'honey_pot', label: 'Honey' },
    { emoji: '🍼', name: 'baby_bottle', label: 'Baby Bottle' },
    { emoji: '🥛', name: 'glass_of_milk', label: 'Milk' },
    { emoji: '☕', name: 'hot_beverage', label: 'Coffee' },
    { emoji: '🫖', name: 'teapot', label: 'Teapot' },
    { emoji: '🍵', name: 'teacup_without_handle', label: 'Tea' },
    { emoji: '🍶', name: 'sake', label: 'Sake' },
    { emoji: '🍾', name: 'bottle_with_popping_cork', label: 'Champagne' },
    { emoji: '🍷', name: 'wine_glass', label: 'Wine' },
    { emoji: '🍸', name: 'cocktail_glass', label: 'Cocktail' },
    { emoji: '🍹', name: 'tropical_drink', label: 'Tropical Drink' },
    { emoji: '🍺', name: 'beer_mug', label: 'Beer' },
    { emoji: '🍻', name: 'clinking_beer_mugs', label: 'Cheers' },
    { emoji: '🥂', name: 'clinking_glasses', label: 'Clinking Glasses' },
    { emoji: '🥃', name: 'tumbler_glass', label: 'Whiskey' },
    { emoji: '🫗', name: 'pouring_liquid', label: 'Pouring' },
    { emoji: '🥤', name: 'cup_with_straw', label: 'Cup with Straw' },
    { emoji: '🧋', name: 'bubble_tea', label: 'Bubble Tea' },
    { emoji: '🧃', name: 'beverage_box', label: 'Juice Box' },
    { emoji: '🧉', name: 'mate', label: 'Mate' },
    { emoji: '🧊', name: 'ice', label: 'Ice' },
    { emoji: '🥢', name: 'chopsticks', label: 'Chopsticks' },
    { emoji: '🍽️', name: 'fork_and_knife_with_plate', label: 'Plate' },
    { emoji: '🍴', name: 'fork_and_knife', label: 'Fork and Knife' },
    { emoji: '🥄', name: 'spoon', label: 'Spoon' },
    { emoji: '🔪', name: 'kitchen_knife', label: 'Knife' },
    { emoji: '🫙', name: 'jar', label: 'Jar' },
    { emoji: '🏺', name: 'amphora', label: 'Amphora' },
  ],
  'Travel & Places': [
    { emoji: '🌍', name: 'globe_showing_europe_africa', label: 'Globe Europe' },
    { emoji: '🌎', name: 'globe_showing_americas', label: 'Globe Americas' },
    { emoji: '🌏', name: 'globe_showing_asia_australia', label: 'Globe Asia' },
    { emoji: '🌐', name: 'globe_with_meridians', label: 'Globe Meridians' },
    { emoji: '🗺️', name: 'world_map', label: 'World Map' },
    { emoji: '🗾', name: 'map_of_japan', label: 'Map of Japan' },
    { emoji: '🧭', name: 'compass', label: 'Compass' },
    { emoji: '🏔️', name: 'snow_capped_mountain', label: 'Snow Mountain' },
    { emoji: '⛰️', name: 'mountain', label: 'Mountain' },
    { emoji: '🌋', name: 'volcano', label: 'Volcano' },
    { emoji: '🗻', name: 'mount_fuji', label: 'Mount Fuji' },
    { emoji: '🏕️', name: 'camping', label: 'Camping' },
    { emoji: '🏖️', name: 'beach_with_umbrella', label: 'Beach' },
    { emoji: '🏜️', name: 'desert', label: 'Desert' },
    { emoji: '🏝️', name: 'desert_island', label: 'Desert Island' },
    { emoji: '🏞️', name: 'national_park', label: 'National Park' },
    { emoji: '🏟️', name: 'stadium', label: 'Stadium' },
    { emoji: '🏛️', name: 'classical_building', label: 'Classical Building' },
    { emoji: '🏗️', name: 'building_construction', label: 'Construction' },
    { emoji: '🧱', name: 'brick', label: 'Brick' },
    { emoji: '🪨', name: 'rock', label: 'Rock' },
    { emoji: '🪵', name: 'wood', label: 'Wood' },
    { emoji: '🛖', name: 'hut', label: 'Hut' },
    { emoji: '🏘️', name: 'houses', label: 'Houses' },
    { emoji: '🏚️', name: 'derelict_house', label: 'Derelict House' },
    { emoji: '🏠', name: 'house', label: 'House' },
    { emoji: '🏡', name: 'house_with_garden', label: 'House with Garden' },
    { emoji: '🏢', name: 'office_building', label: 'Office Building' },
    { emoji: '🏣', name: 'japanese_post_office', label: 'Post Office' },
    { emoji: '🏤', name: 'post_office', label: 'European Post Office' },
    { emoji: '🏥', name: 'hospital', label: 'Hospital' },
    { emoji: '🏦', name: 'bank', label: 'Bank' },
    { emoji: '🏨', name: 'hotel', label: 'Hotel' },
    { emoji: '🏩', name: 'love_hotel', label: 'Love Hotel' },
    { emoji: '🏪', name: 'convenience_store', label: 'Convenience Store' },
    { emoji: '🏫', name: 'school', label: 'School' },
    { emoji: '🏬', name: 'department_store', label: 'Department Store' },
    { emoji: '🏭', name: 'factory', label: 'Factory' },
    { emoji: '🏯', name: 'japanese_castle', label: 'Japanese Castle' },
    { emoji: '🏰', name: 'castle', label: 'Castle' },
    { emoji: '💒', name: 'wedding', label: 'Wedding' },
    { emoji: '🗼', name: 'tokyo_tower', label: 'Tokyo Tower' },
    { emoji: '🗽', name: 'statue_of_liberty', label: 'Statue of Liberty' },
    { emoji: '⛪', name: 'church', label: 'Church' },
    { emoji: '🕌', name: 'mosque', label: 'Mosque' },
    { emoji: '🛕', name: 'hindu_temple', label: 'Hindu Temple' },
    { emoji: '🕍', name: 'synagogue', label: 'Synagogue' },
    { emoji: '⛩️', name: 'shinto_shrine', label: 'Shinto Shrine' },
    { emoji: '🕋', name: 'kaaba', label: 'Kaaba' },
    { emoji: '⛲', name: 'fountain', label: 'Fountain' },
    { emoji: '⛺', name: 'tent', label: 'Tent' },
    { emoji: '🌁', name: 'foggy', label: 'Foggy' },
    { emoji: '🌃', name: 'night_with_stars', label: 'Night Stars' },
    { emoji: '🏙️', name: 'cityscape', label: 'Cityscape' },
    { emoji: '🌄', name: 'sunrise_over_mountains', label: 'Sunrise Mountains' },
    { emoji: '🌅', name: 'sunrise', label: 'Sunrise' },
    { emoji: '🌆', name: 'cityscape_at_dusk', label: 'City Dusk' },
    { emoji: '🌇', name: 'sunset', label: 'Sunset' },
    { emoji: '🌉', name: 'bridge_at_night', label: 'Bridge Night' },
    { emoji: '♨️', name: 'hot_springs', label: 'Hot Springs' },
    { emoji: '🎠', name: 'carousel_horse', label: 'Carousel' },
    { emoji: '🎡', name: 'ferris_wheel', label: 'Ferris Wheel' },
    { emoji: '🎢', name: 'roller_coaster', label: 'Roller Coaster' },
    { emoji: '💈', name: 'barber_pole', label: 'Barber Pole' },
    { emoji: '🎪', name: 'circus_tent', label: 'Circus Tent' },
    { emoji: '🚂', name: 'locomotive', label: 'Locomotive' },
    { emoji: '🚃', name: 'railway_car', label: 'Railway Car' },
    { emoji: '🚄', name: 'high_speed_train', label: 'High Speed Train' },
    { emoji: '🚅', name: 'bullet_train', label: 'Bullet Train' },
    { emoji: '🚆', name: 'train', label: 'Train' },
    { emoji: '🚇', name: 'metro', label: 'Metro' },
    { emoji: '🚈', name: 'light_rail', label: 'Light Rail' },
    { emoji: '🚉', name: 'station', label: 'Station' },
    { emoji: '🚊', name: 'tram', label: 'Tram' },
    { emoji: '🚝', name: 'monorail', label: 'Monorail' },
    { emoji: '🚞', name: 'mountain_railway', label: 'Mountain Railway' },
    { emoji: '🚋', name: 'tram_car', label: 'Tram Car' },
    { emoji: '🚌', name: 'bus', label: 'Bus' },
    { emoji: '🚍', name: 'oncoming_bus', label: 'Oncoming Bus' },
    { emoji: '🚎', name: 'trolleybus', label: 'Trolleybus' },
    { emoji: '🚐', name: 'minibus', label: 'Minibus' },
    { emoji: '🚑', name: 'ambulance', label: 'Ambulance' },
    { emoji: '🚒', name: 'fire_engine', label: 'Fire Engine' },
    { emoji: '🚓', name: 'police_car', label: 'Police Car' },
    { emoji: '🚔', name: 'oncoming_police_car', label: 'Oncoming Police' },
    { emoji: '🚕', name: 'taxi', label: 'Taxi' },
    { emoji: '🚖', name: 'oncoming_taxi', label: 'Oncoming Taxi' },
    { emoji: '🚗', name: 'automobile', label: 'Car' },
    { emoji: '🚘', name: 'oncoming_automobile', label: 'Oncoming Car' },
    { emoji: '🚙', name: 'sport_utility_vehicle', label: 'SUV' },
    { emoji: '🛻', name: 'pickup_truck', label: 'Pickup Truck' },
    { emoji: '🚚', name: 'delivery_truck', label: 'Delivery Truck' },
    { emoji: '🚛', name: 'articulated_lorry', label: 'Truck' },
    { emoji: '🚜', name: 'tractor', label: 'Tractor' },
    { emoji: '🏎️', name: 'racing_car', label: 'Racing Car' },
    { emoji: '🏍️', name: 'motorcycle', label: 'Motorcycle' },
    { emoji: '🛵', name: 'motor_scooter', label: 'Scooter' },
    { emoji: '🦽', name: 'manual_wheelchair', label: 'Wheelchair' },
    { emoji: '🦼', name: 'motorized_wheelchair', label: 'Motorized Wheelchair' },
    { emoji: '🛺', name: 'auto_rickshaw', label: 'Rickshaw' },
    { emoji: '🚲', name: 'bicycle', label: 'Bicycle' },
    { emoji: '🛴', name: 'kick_scooter', label: 'Kick Scooter' },
    { emoji: '🛹', name: 'skateboard', label: 'Skateboard' },
    { emoji: '🛼', name: 'roller_skate', label: 'Roller Skate' },
    { emoji: '🚏', name: 'bus_stop', label: 'Bus Stop' },
    { emoji: '🛣️', name: 'motorway', label: 'Motorway' },
    { emoji: '🛤️', name: 'railway_track', label: 'Railway Track' },
    { emoji: '🛢️', name: 'oil_drum', label: 'Oil Drum' },
    { emoji: '⛽', name: 'fuel_pump', label: 'Fuel Pump' },
    { emoji: '🛞', name: 'wheel', label: 'Wheel' },
    { emoji: '🚨', name: 'police_car_light', label: 'Police Light' },
    { emoji: '🚥', name: 'horizontal_traffic_light', label: 'Traffic Light H' },
    { emoji: '🚦', name: 'vertical_traffic_light', label: 'Traffic Light' },
    { emoji: '🛑', name: 'stop_sign', label: 'Stop Sign' },
    { emoji: '🚧', name: 'construction', label: 'Construction Sign' },
    { emoji: '⚓', name: 'anchor', label: 'Anchor' },
    { emoji: '⛵', name: 'sailboat', label: 'Sailboat' },
    { emoji: '🛶', name: 'canoe', label: 'Canoe' },
    { emoji: '🚤', name: 'speedboat', label: 'Speedboat' },
    { emoji: '🛳️', name: 'passenger_ship', label: 'Passenger Ship' },
    { emoji: '⛴️', name: 'ferry', label: 'Ferry' },
    { emoji: '🛥️', name: 'motor_boat', label: 'Motor Boat' },
    { emoji: '🚢', name: 'ship', label: 'Ship' },
    { emoji: '✈️', name: 'airplane', label: 'Airplane' },
    { emoji: '🛩️', name: 'small_airplane', label: 'Small Airplane' },
    { emoji: '🛫', name: 'airplane_departure', label: 'Airplane Departure' },
    { emoji: '🛬', name: 'airplane_arrival', label: 'Airplane Arrival' },
    { emoji: '🪂', name: 'parachute', label: 'Parachute' },
    { emoji: '💺', name: 'seat', label: 'Seat' },
    { emoji: '🚁', name: 'helicopter', label: 'Helicopter' },
    { emoji: '🚟', name: 'suspension_railway', label: 'Suspension Railway' },
    { emoji: '🚠', name: 'mountain_cableway', label: 'Mountain Cableway' },
    { emoji: '🚡', name: 'aerial_tramway', label: 'Aerial Tramway' },
    { emoji: '🛰️', name: 'satellite', label: 'Satellite' },
    { emoji: '🚀', name: 'rocket', label: 'Rocket' },
    { emoji: '🛸', name: 'flying_saucer', label: 'UFO' },
  ]
}
